### ISSUE TITLE
Social/Magic Login for Unity

### ISSUE THREAD

**Issue by cipherzzz** [MoralisWeb3/web3-unity-sdk#44]
Hey team - I'm investigating using your product for a metaverse project but it seems like you only support an email login or a wallet connection for authentication. Do you not support an alternative methods in your AuthenticationKit such as social login or magic? I see the node examples but not sure if there is a C# implementation for Unity?

**Comment by xactant** [comment]
These are currently some-what usable but you will need to do your own integration. if you check the docs (docs.moralis.io) there are instructions for how to set up email verification
