### ISSUE TITLE
I keep getting 'MoralisUnity' could not be found

### ISSUE THREAD

**Issue by hameedjb** [MoralisWeb3/web3-unity-sdk#57]
The type or namespace name 'MoralisUnity' could not be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp]csharp(CS0246)

I've imported web3-unity-sdk and entered all my dapp info, still getting this error, also for Netherum and Cysharp, any solutions?

thanks.

**Comment by KoenRijpstra** [comment]
How did you import the web3-unity-sdk?
